import type { Material } from '../types';

export const materials: Material[] = [
  {
    id: 'pla',
    name: 'PLA (聚乳酸)',
    category: '核心基礎耗材',
    features: ['入門首選', '環保無毒', '低熱收縮率'],
    description: '原料來自玉米或甘蔗澱粉，環保無毒，列印時帶有微甜的氣味。它的熱收縮率極低，幾乎不會翹曲。',
    pros: ['易於列印', '表面細緻', '氣味友善'],
    cons: ['質地較脆', '耐熱性差 (約 60°C 軟化)'],
    applications: ['概念模型', '公仔', '展示品', '教學用途'],
  },
  {
    id: 'petg',
    name: 'PETG (聚對苯二甲酸乙二醇酯)',
    category: '核心基礎耗材',
    features: ['剛柔並濟', '防水性佳', '化學穩定'],
    description: '結合了 PLA 的易印性與 ABS 的強度。具有極佳的層間黏合力、防水性與化學穩定性，微帶韌性且不易碎。',
    pros: ['強度高', '耐候性好', '不易碎'],
    cons: ['容易吸濕', '易拉絲', '易黏噴嘴'],
    applications: ['機械功能件', '生活結構件', '戶外防水物件'],
  },
  {
    id: 'abs-asa',
    name: 'ABS / ASA',
    category: '核心基礎耗材',
    features: ['耐熱', '高強度', '耐衝擊'],
    description: 'ABS 強度高、耐衝擊，耐熱可達 100°C。ASA 性質相似但具備抗紫外線功能。',
    pros: ['耐熱性佳', '可丙酮拋光 (ABS)', '抗 UV (ASA)'],
    cons: ['收縮顯著', '易翹曲', '有毒性煙霧'],
    applications: ['汽車零件', '工具外殼', '戶外耐候產品'],
  },
  {
    id: 'tpu',
    name: 'TPU / TPE',
    category: '特殊與進階耗材',
    features: ['高彈性', '耐磨', '吸震'],
    description: '成品就像橡膠一樣，具有極佳的耐磨性、吸震能力、拉伸性與彈性，幾乎不會翹曲。',
    pros: ['極佳韌性', '耐磨損', '不易翹曲'],
    cons: ['列印速度慢', '對擠出機要求高'],
    applications: ['手機保護殼', '避震墊圈', '鞋墊', '穿戴式裝置'],
  },
  {
    id: 'nylon',
    name: 'Nylon (尼龍 / PA)',
    category: '特殊與進階耗材',
    features: ['極高耐磨', '強韌', '自潤滑'],
    description: '兼具強大的韌性、耐磨性與自潤滑性，抗衝擊能力頂級。',
    pros: ['工業級強度', '耐摩擦'],
    cons: ['極易吸濕', '列印難度高', '需高溫設備'],
    applications: ['機械齒輪', '卡扣', '承軸', '高強度承重件'],
  },
  {
    id: 'composite',
    name: '碳纖維 / 玻璃纖維複合線材',
    category: '特殊與進階耗材',
    features: ['高剛性', '抗拉強度', '霧面質感'],
    description: '在基材中加入短纖維，大幅提升剛性與抗拉強度，降低收縮率。',
    pros: ['尺寸穩定', '極高剛性', '外觀專業'],
    cons: ['磨損噴嘴', '層間結合稍弱'],
    applications: ['無人機機架', '賽車輕量化零件', '工業級高剛性治具'],
  },
];
